### ISSUE TITLE
[FEATURE] Add ability to specify each node's user name, password, and hosts if known

### ISSUE THREAD

**Issue by davidallendj** [OpenCHAMI/magellan#2]
## Description of Issue

There are some situations where it is possible to have nodes in a cluster with different BMC login credentials. In these situations, it would be necessary to be able to specify each individual node's login information opposed to only using to the one specified currently. 

This feature is necessary for **static discovery** (i.e. nodes are known and specified beforehand without out performing a scan) and is already possible to specify individual credentials with the `crawler` package. However, it is not possible to specify the credentials with the CLI or using a file.

Additionally, there needs to be a way to specify credentials with **dynamic discovery** (i.e. performing a scan to find devices/BMC nodes). This may be done after the scan in a similar fashion to static discovery, but the has to be a way to set the credentials using the cached information, which may require updating the cache schema.

## Possible Solutions

There are at least three approaches to consider here. We can specify the BMC node information via: 

1. a YAML config file
2. environment variables
3. CLI flags

Using a config file may look something like this:

```yaml
...
collect:
  nodes:
    - host: 172.16.0.101
      username: "username1"
      password: "password1"
    - host: 172.16.0.102
      username: "username2"
      password: "password2"
    # alternatively...
    - host: 172.16.0.103
      user: "username3:password3"
...
```

The corresponding environment variable may look similar as a single comma-delimited string with syntax "host:username:password":

```bash
export MAGELLAN_COLLECT_NODES="172.16.0.101:username1:password1,172.16.0.102:username2:password2,172.16.0.103:username3:password3"
```

And finally, the CLI flags:

```bash
magellan collect \
    --node "172.16.0.101:username1:password1" \
    --node "172.16.0.102:username2:password2" \
    --node "172.16.0.103:username3:password3"
```

The new method would possibly deprecate the old `--username` and `--password` flags in favor of a single `--node` flag instead. Alternatively, the `--username` and `--password` flags could be used as the default parameter if the `--node` flag is not set for a node.

## Other Considerations

Specifying the login information in the config file may not be ideal unless the config file exists in a location that requires elevated admin privileges. Therefore, it may be more advantageous to use environment variables or CLI flags as mentioned above in the "Possible Solutions" section.

Migrated from https://github.com/bikeshack/magellan/issues/6.
