### ISSUE TITLE
Testing Magellan with Redfish Emulators

### ISSUE THREAD

**Issue by davidallendj** [OpenCHAMI/magellan#76]
There seems to be a desire to test `magellan`'s compatibility with a stable Redfish implementation using an emulator such as [sushy-tools](https://github.com/openstack/sushy-tools). Upon evaluating the emulator, I found that running the emulator itself if straight-forward using docker-compose. However, when making requests to certain Redfish endpoints, the emulator tries to query hardware information from a `libvirtd` virtual machine. Setting up and including a virtual machine is out of scope of the project.

The docker compose YAML:

```yaml
services:
  sushy-emulator:
    image: quay.io/metal3-io/sushy-tools:latest
    container_name: sushy-tools
    volumes:
      - ./conf.py:/etc/sushy/sushy-emulator.conf:Z
      - /var/run/libvirt:/var/run/libvirt:Z
    ports:
      - 8000:8000
    environment:
      SUSHY_EMULATOR_CONFIG: /etc/sushy/sushy-emulator.conf
```

The configuration file that goes with it:

```python
SUSHY_EMULATOR_LISTEN_IP = u'0.0.0.0'
SUSHY_EMULATOR_LISTEN_PORT = 8000
SUSHY_EMULATOR_SSL_CERT = None
SUSHY_EMULATOR_SSL_KEY = None
SUSHY_EMULATOR_OS_CLOUD = None
SUSHY_EMULATOR_LIBVIRT_URI = u'qemu:///system'
SUSHY_EMULATOR_IGNORE_BOOT_DEVICE = True
SUSHY_EMULATOR_BOOT_LOADER_MAP = {
    u'UEFI': {
        u'x86_64': u'/usr/share/OVMF/OVMF_CODE.secboot.fd'
    },
    u'Legacy': {
        u'x86_64': None
    }
}
```

Finally, invoke with docker compose:

```bash
docker compose -f emulator/sushy/sushy-tools.yml up
```

Alternatively, the repository already includes a Redfish emulator that can be used for testing `magellan`. To start the currently existing emulator, run the `emulator/setup.sh` script or `make emulator`.
